# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - claw_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - base_link_link1
      - link1_link2
      - link2_link3
      - link3_link4
      - link4_link5
      - link5_link6
      - link6_end_effector
    action_ns: follow_joint_trajectory
    default: true

  claw_controller:
    type: FollowJointTrajectory
    joints:
      - claw_base_finger_one
    action_ns: follow_joint_trajectory
    default: true